#!/usr/bin/env python
"""
Convert the output of ms to an N-dimensional site frequency spectrum.
"""
import cPickle
import sys

import numpy

import dadi.IO

if __name__ == '__main__':
    average = ('-av' in sys.argv)
    report_sum = ('-sum' in sys.argv)
    
    input = sys.stdin
    output = sys.stdout
    sfs,header = dadi.IO.sfs_from_ms_file(input, average, sum, 
                                           return_header=True)
    
    dadi.IO.sfs_to_file(sfs, output, comment_lines=header)
