name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add micromamba to system path and install dependencies
      uses: mamba-org/setup-micromamba@main
      with:
        environment-name: dadi
        activate-environment: dadi
        environment-file: build-env.yml
    - name: Test with pytest
      run: |
        pytest -v tests/test_*.py
