name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Add micromamba to system path
      uses: mamba-org/setup-micromamba@main
      with:
        environment-name: dadi
        activate-environment: dadi
        environment-file: build-env.yml
    - name: Test with pytest
      run: |
        micromamba run -n dadi pytest -v
